Traceback (most recent call last):
  File "gen_data.py", line 356, in <module>
    ga_instance.run()
  File "/home/macula/SMATousi/.conda/envs/mac-deep/lib/python3.7/site-packages/pygad/pygad.py", line 1724, in run
    self.last_generation_fitness = self.cal_pop_fitness()
  File "/home/macula/SMATousi/.conda/envs/mac-deep/lib/python3.7/site-packages/pygad/pygad.py", line 1542, in cal_pop_fitness
    fitness = self.fitness_func(self, sol, sol_idx)
  File "gen_data.py", line 170, in fitness_func_avg
    avg_ins = avg_ins.reshape([1,30])
ValueError: cannot reshape array of size 100 into shape (1,30)